### ISSUE TITLE
Cannot redeclare functions

### ISSUE THREAD

**Issue by ghost** [shibdib/API-Registration-Mod-Revisited#4]
Every time I've tried to install this mod, I keep getting errors like:

```
Fatal error: Cannot redeclare cronlog() (previously declared in /var/www/html/test.com/forum/includes/eveapi/functions_eveapi.php:25) in /var/www/html/test.com/forum/includes/eveapi/functions_eveapi.php on line 25
```

I have no idea why.  even when I put debug messages inside "functions_eveapi.php", it only executes once and that is the only place in all my files that those functions get declared in

**Comment by shibdib** [comment]
Is this with a fresh install?

(been super busy with rl sorry for the slow response)
