### ISSUE TITLE
Database incomplete

### ISSUE THREAD

**Issue by Nadarob-Skillane** [shibdib/API-Registration-Mod-Revisited#5]
The current database is incomplete - a lot of basic items are missing (Medium Shield Extender II for example)
having a look at the function_eve_items.php install file from a previous version, the amount of missing items numbers approximately 5,000.

**Comment by shibdib** [comment]
will look into this, might have messed up the export from sde

**Comment by shibdib** [comment]
https://github.com/shibdib/API-Registration-Mod-Revisited/commit/c686690bb4382d2a93cb16a62e96c2c1b4ce4f07

Readme updated with how to install the latest database, super easy :).
